sciunto-org/python-bibtexparser

bibtexparser/__init__.py
bibtexparser/bparser.py
bibtexparser/bwriter.py
bibtexparser/customization.py

Relative imports

---

docs/source/tutorial.rst

Fix filename in tutorial: @geritwagner 	bibfile -> bibtex_file

bibfile -> bibtex_file

---

bibtexparser/bibdatabase.py
setup.py

Writing a bibtex file previously failed if there were unicode characters in any entry fields.

Fix unicode write

---

bibtexparser/bwriter.py
bibtexparser/tests/test_bibtexwriter.py

1. align_values checks how wide the longest key is in the whole bib-database and aligns all values according to this maximal width
2. display_order allows to have custom ordering of the fields of each entry instead of just alphabetical
The according unit tests are added as well.

two more features for bibtexwriter

---

bibtexparser/tests/data/article_oneline.bib
bibtexparser/tests/test_bparser.py
tox.ini

[WIP] Handle one line records

---

CHANGELOG
bibtexparser/bparser.py
bibtexparser/customization.py
bibtexparser/tests/test_bparser.py
bibtexparser/tests/test_customization.py
bibtexparser/tests/test_homogenise_fields.py
docs/source/tutorial.rst

Fixes #94. Unittest already implemented.

Defaultvalue

---

bibtexparser/bibtexexpression.py
bibtexparser/bparser.py

support parenthesis in field syntax #124

---

docs/source/logging.rst
docs/source/tutorial.rst

Thanks for designing a simple tool with the minimal API required for the job.

DOC: minor typos

---

bibtexparser/__init__.py
bibtexparser/tests/test_bibtexwriter.py

This should implement the fix described in #51.
Closes #51.

Fix for #51

---

.travis.yml

Fix Travis build with pypy3

---

bibtexparser/bparser.py
bibtexparser/customization.py
docs/source/bibtexparser.rst
docs/source/conf.py
docs/source/tutorial.rst

Fix tutorial and minor build issues in documentation

---

.travis.yml

Fixes #217 
@omangin I let you review and merge.

add python 3.7 to travis

---

bibtexparser/bibtexexpression.py

See note on API change with 2.3.1 in pyparsing's changelog:
https://github.com/pyparsing/pyparsing/blob/master/CHANGES

Fixes #225.

---

bibtexparser/customization.py

Use https://doi.org/ for DOIs

---

CHANGELOG
bibtexparser/__init__.py

Prepare next release.

---

bibtexparser/tests/test_customization.py
docs/source/demo.py

Fix tutorial demo

---

RELEASE

:wrench: update RELEASE instructions

---

bibtexparser/bparser.py

:bulb: Fix Mistake in Documentation

---

.github/workflows/tests.yml

...its not supported anymore...

:green_heart: Remove github action for python 3.6

---

.github/workflows/codeql-analysis.yml
.github/workflows/linting_and_unittests.yml
bibtexparser/entrypoint.py
bibtexparser/exceptions.py
bibtexparser/middlewares/interpolate.py
bibtexparser/middlewares/latex_encoding.py
bibtexparser/middlewares/middleware.py
bibtexparser/middlewares/month.py
bibtexparser/middlewares/names.py
bibtexparser/middlewares/sorting_blocks.py
bibtexparser/middlewares/sorting_entry_fields.py
bibtexparser/model.py
bibtexparser/splitter.py
bibtexparser/writer.py
setup.py
tests/middleware_tests/test_enclosing.py
tests/middleware_tests/test_interpolate.py
tests/middleware_tests/test_month.py
tests/middleware_tests/test_names.py
tests/middleware_tests/test_sorting_blocks.py
tests/middleware_tests/test_sorting_entry_fields.py
tests/splitter_tests/test_splitter_entry.py
tests/test_writer.py

This was intended to be done as part of #341, which seems to be stale - and I cannot really wait any longer.
This PR does not make #341 obsolete, but it allows to run CI tasks already waiting while we change for the build architecture change (which is the main part of #341)

:rotating_light: Linting and GitHub Actions for `v2`

---

tests/middleware_tests/test_latex_encoding.py

:white_check_mark: Implement test case provided in #272

---

tests/splitter_tests/test_splitter_string.py

:white_check_mark: Test empty string

---

.readthedocs.yaml

:pencil: Create .readthedocs.yaml

---

bibtexparser/model.py
tests/test_model.py

:sparkles: Allow deletion of fields on entries by key 

---

.github/workflows/linting_and_unittests.yml

Workaround for problems with setup-python: https://github.com/actions/setup-python/issues/855

:green_heart: Workaround for macos ci issues
