sciunto-org/python-bibtexparser

bibtexparser/bwriter.py, bibtexparser/tests/data/article_comma_first.bib, bibtexparser/tests/data/book_comma_first.bib
changes:
```
@book{Bird1987
,   author = {Bird, R.B. and Armstrong, R.C. and Hassager, O.}
,   edition = {2}
,   publisher = {Wiley Edition}
,   title = {Dynamics of Polymeric Liquid}
,   volume = {1}
,   year = {1987}
}
```
to:
```
@book{Bird1987
, author = {Bird, R.B. and Armstrong, R.C. and Hassager, O.}
, edition = {2}
, publisher = {Wiley Edition}
, title = {Dynamics of Polymeric Liquid}
, volume = {1}
, year = {1987}
}
```
which preserves visual indentation.
edit: placed examples within code blocks
=> place comma after indent for comma_first=True in bwriter

bibtexparser/bparser.py
Hi,
Currently @STRING macro can have a trailing '}' character after parsing. For example:
```
@STRING{oakland = {Proceedings of the {IEEE} Symposium on Security and Privacy}}
@INPROCEEDINGS{cha:oakland15,
author = {Sang Kil Cha and Maverick Woo and David Brumley},
title = {{Program-Adaptive Mutational Fuzzing}},
booktitle = oakland,
year = {2015},
pages = {725--741}
}
```
When we parse the above bibtex entry, the 'booktitle' field contains
**Proceedings of the {IEEE} Symposium on Security and Privacy},**
with extra '},'.
The root cause of this bug is due the wrong order of *strip* calls. This patch will fix this bug.
Best Regards,
Sang Kil
=> BUGFIX: @STRING records have a trailing '}' character

bibtexparser/tests/data/comments_percentage.bib, bibtexparser/tests/data/comments_percentage_nolastcoma.bib, bibtexparser/tests/test_comments.py
See #45 for a full discussion.
This branch integrates a test that reproduces the issue. The test is skipped and must be addressed.
=> [WIP] Regression comments starting with % and no final coma

bibtexparser/bparser.py, bibtexparser/tests/test_bparser.py
This functionality is now directly handled by the parsing grammar.
Also removes the related tests.
=> Removes unused code for stripping braces and quotes.

bibtexparser/bibtexexpression.py, bibtexparser/tests/data/article_no_braces.bib, bibtexparser/tests/data/article_with_special_characters.bib, bibtexparser/tests/test_bparser.py
=> Fixes test failure if title contains {\"u} et no outer { }

.gitignore, CONTRIBUTORS.txt, bibtexparser/customization.py, bibtexparser/tests/test_splitname.py, docs/source/bibtexparser.rst
This pull request adds a `splitname()` function to the customization module. It takes a single name as a string, splits it up into the first / von / last / jr parts as per BibTeX, and returns a dictionary. Splitting the string into words is accomplished in a single pass over the string, and then the words are divided up into parts as per BibTeX. Basic error checking is performed while dividing it up into words, and can be suppressed and automatically corrected by setting the `strict_mode` parameter to False.
A large number of testcases are added. Many of these are taken from [Xavier Décoret's BibTeX reference page](http://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html#names) and the [unit tests](https://bitbucket.org/pybtex-devs/pybtex/src/1819074df33ae76f95b3701 …
=> Add customization.splitname() function

bibtexparser/customization.py, bibtexparser/latexenc.py, bibtexparser/tests/test_customization.py
`convert_to_unicode` customization was converting `\"u` (without braces)
to `\u0308u` which was supposed to be an `u` letter with an umlaut.
However, the `\u0308` unicode character is supposed to be *after* the
letter, contrary to the LaTeX encoding of the accent.
This commit fixes it and additionally wrap the `convert_to_unicode`
customization in a dedicated function that could be reused.
Also makes the fix for every other combining diacritic mark.
Closes #121.
@sciunto Sorry for the mess with the previous PR, I just got mixed up with the state of my fork on my two laptops :/ This PR should pass all the tests (at least it does on my laptop). I am waiting for Travis feedback.
=> Fix `convert_to_unicode` for unbraced sequences

bibtexparser/customization.py, bibtexparser/tests/test_customization.py, requirements.txt
Add a `add_plaintext_fields` customization to strip fields of braces and
similar characters, getting only the plaintext. It processes every
available fields and for each field, it adds a `plain_*` field
containing the plaintext version.
Should close #116.
=> Customization to strip fields of `{`, `}` etc

bibtexparser/latexenc.py, bibtexparser/tests/test_customization.py
When using the `convert_to_unicode` customization, braces should be
stripped from the output.
This closes #161.
=> Strip braces from `convert_to_unicode` output

bibtexparser/bparser.py, bibtexparser/tests/data/article_homogenize.bib, bibtexparser/tests/data/website.bib, bibtexparser/tests/test_homogenise_fields.py
- `urls`, `link`, and `links` are now replaced by `url`,
- adds some test to homogenize_fields.
=> Fix: url replaced to link on homogenize_fields (#171)

bibtexparser/bparser.py, bibtexparser/tests/data/book_bom.bib, bibtexparser/tests/test_bibtexparser.py
BOM detection didn't work in python3 so bib files with utf-8-bom was not read into database.
=> fixed problem that BOM recognition doesn't actually work

bibtexparser/bparser.py, bibtexparser/tests/test_bparser.py
– better test coverage for the `ignore_nonstandard` parameter (see #143),
– more documentation on `BibtexParser` parameters,
– small cleanup in `test_bparser`.
=> Minor fixes

bibtexparser/latexenc.py, bibtexparser/tests/test_latexenc.py
Simplifies `latex_to_unicode` and fixes modifier orders.
In particular this fixes indiscriminate reorder of unicode modifiers. When the string already contained unicode modifiers these would be moved inappropriately to the next character by `latex_to_unicode`. For example `"Jalapeño" #  u"Jalapen\u0303o"'` would be changed to `"Jalapenõ"  #  u"Jalapen\u00f5"`.
=> Fix invalid reorders of unicode combining in latexenc

bibtexparser/bibtexexpression.py, bibtexparser/tests/data/comments_spaces_and_declarations.bib, bibtexparser/tests/test_bibtexexpression.py, bibtexparser/tests/test_bparser.py
(See #198)
The parser currently skips declarations preceded by a space after a comment:
they are considered part of the implicit comment before. This behavior differs,
for example, from what biber would do on the same file. It is also not consistent
with the fact that a line started as " @string" is a valid string declaration.
=> Handles declarations on lines starting with spaces after comments.

bibtexparser/bibtexexpression.py
For me on Ubuntu 14.04 LTS, with `python-bibtexparser` installed through pip3 (`--user`), `loads(...)` fails at that expression with:
```
File "$HOME/.local/lib/python3.4/site-packages/bibtexparser/bibtexexpression.py", line 180, in __init__
) | pp.stringEnd()
TypeError: __call__() missing 1 required positional argument: 'name'
```
After a quick search I found out, that pyparsing functions are usually upper-case. I then changed `stringEnd`  to `StringEnd`, which made it work. I don't know whether this is a API change in pyparsing or whatever, so please excuse me if this is intentinal. I just thought I leave it here for you to investigate.
```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
$ python3 …
```
=> Fix typo in pp.StringEnd

bibtexparser/bibtexexpression.py, bibtexparser/tests/data/article_with_annotation.bib, bibtexparser/tests/data/article_with_annotation_output.bib, bibtexparser/tests/test_bparser.py, bibtexparser/tests/test_bwriter.py
BibLaTeX-style annotations result in entries being incorrectly parsed as `ImplicitComment`. 
For example, the following article entry will not parse because it contains "author+an":
```
@ARTICLE{Cesar2013,
author = {Jean César},
author+an = {1=highlight},
title = {An amazing title},
year = {2013},
month = "jan",
volume = {12},
pages = {12-23},
journal = {Nice Journal},
abstract = {This is an abstract. This line should be long enough to test
multilines... and with a french érudit word},
comments = {A comment},
keyword = {keyword1, keyword2},
}
```
Support BibLaTeX-style annotations in entries by allowing the plus sign (+) in a field names. No support to use the annotations in any way is added.
* [BibLaTeX Documentation](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/bibla …
=> Add support for BibLaTeX annotations

bibtexparser/bibdatabase.py, bibtexparser/bparser.py, bibtexparser/tests/data/biber-examples.bib, bibtexparser/tests/data/crossref_cascading.bib, bibtexparser/tests/data/crossref_cascading_aliases.bib, bibtexparser/tests/data/crossref_cascading_cycle.bib, bibtexparser/tests/data/crossref_entries.bib, bibtexparser/tests/data/crossref_missing_entries.bib, bibtexparser/tests/data/xref_entries.bib, bibtexparser/tests/data/xref_missing_entries.bib, bibtexparser/tests/test_crossref_resolving.py, requirements.txt, setup.py
bibtexparser does currently not resolve cross references. This pull request adds the support.
It is based on #109 by @flopraden, credit for the feature goes to him.
This pull request deprecates #109 and expands on it:
- Rebased onto master
- Commit message style fixed
- Failing unit tests fixed
- Clarified BibTeX assumptions
- Typos and minor fixes 
* [BibLaTeX Documentation](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf), Section 2.2.3 Special Fields (page 26)
=> Feature: crossref Support

bibtexparser/bibdatabase.py, bibtexparser/bparser.py
Previously missing from PR #216. 
Adds:
- Documentation for `add_missing_from_crossref` argument of `bparser`
- Documentation for public method `add_missing_from_crossref` for `BibDatabase`
=> Add very basic crossref documentation

bibtexparser/bibtexexpression.py, bibtexparser/tests/test_bibtexexpression.py, bibtexparser/tests/test_bparser.py
Fixes #163.
Prevents empty citekeys and whitespaces in citekeys at parse time.
=> Checks for empty citekeys and whitespaces.

bibtexparser/bibdatabase.py, bibtexparser/bparser.py, bibtexparser/bwriter.py, bibtexparser/customization.py, bibtexparser/latexenc.py
I came across this while packaging python-bibtexparser for Fedora. See
https://bugzilla.redhat.com/show_bug.cgi?id=1812973
Signed-off-by: W. Michael Petullo <mike@flyn.org>
=> Remove shebang lines from non-executable Python files

bibtexparser/tests/test_customization.py
strings containing regular expressions are now properly quoted.
=> closes #266 - strings containing regular expressions are now properly quoted.

bibtexparser/tests/test_bibtexparser.py, bibtexparser/tests/test_bibtexwriter.py, bibtexparser/tests/test_bparser.py
Currently, the tests depend on the system they are run on, in terms of assumed file encoding. 
This leads to tests that pass on the CI, but fail locally. 
This PR makes the encodings in the test files explicit.
=> :white_check_mark: Fix file encoding in tests

bibtexparser/tests/test_bibtexparser.py
Verify that empty bib files lead to empty bib database.
=> :white_check_mark: Add test covering empty bib files

bibtexparser/bparser.py, bibtexparser/tests/test_bibtex_strings.py, bibtexparser/tests/test_bparser.py, bibtexparser/tests/test_comments.py
Having to manually enable common strings appears to be one of the biggest unexpected behaviors, leading to plenty of questions.
Making the use of common strings a default does not fix all problems (e.g., people wanting to get non-interpolated, string values), but it should be a crucial first step and - most importantly - makes the default config more natural and intuitive for new users.
Not many negative side effects are expected from this. The old behavior can easily be enabled by creating a parser with `common_strings=False`
Fixes #280
Fixes #263
Fixes #248
=> :wrench: using common strings is now the default

bibtexparser/bwriter.py, bibtexparser/tests/data/article_multilines.bib, bibtexparser/tests/test_bibtexwriter.py
A new option `align_multiline_values` is added to BibTexWriter to enable whether text of multiline values should be aligned on top of each other. Indentation also considered `_max_field_width`.
Current behaviour:
BibTeX entry:
```
@article{test,
title     = {Hello World. I'm a very very very
very very very very long title. Hello Bibtex Parser!
This is still a long title!},
}
```
Parsing with BibtexParser will result in:
```
@article{test,
title = {Hello World. I'm a very very very
very very very very long title. Hello Bibtex Parser!
This is still a long title!}
}
```
When `align_multiline_values` is set to true, the output will be the
following:
```
@article{test,
title = {Hello World. I'm a very very very
very very very very long title. Hello Bibtex Parser!
This is still a long title!}
} …
```
=> ✨ Add option to adjust alignment of text of multi-line values.

.gitignore, bibtexparser/bparser.py, bibtexparser/tests/data/article_comma_normal_multiple.bib, bibtexparser/tests/data/article_comma_normal_single.bib, bibtexparser/tests/test_bparser.py
Fixes https://github.com/sciunto-org/python-bibtexparser/issues/308. A warning message will appear if the `parse` method is called more than once and the message will be "Parser has been called more than once."
=> :children_crossing: Raise warning if parser is used multiple times

bibtexparser/bwriter.py, bibtexparser/tests/test_bibtexwriter.py
Fixes #277
Add different sorting strategies for elements that are added at the end of `display_order`. I'm not sure if we should use a `enum` for `display_order_sorting` or any other global value.. A enum is most convenient I think.
=> ✨Allow preservation of existing order of entry fields in writer

bibtexparser/bwriter.py, bibtexparser/tests/test_bibtexwriter.py
Fixes #315
Aligns all values according to a given length by padding with single spaces. If align_values is true, the maximum number of characters used in any field name is used as the length. If align_values is a number, the greater of the specified value or the maximum number of characters used in any field name is used as the length.
> **_NOTE_:**: This commit includes breaking changes: The `ENTRYTYPE` entry was considered for calculating the maximum number of characters for entries, which always lead to a minimum value of `9`. Now, keys that are not written as BibTeX output are ignored, which leads to an exact computation of the number of characters for entries.
=> :bug: align_values allows int or bool, fixes previous min alignment

bibtexparser/__init__.py
This PR is with reference to #329. Please check if there are any inaccuracies.
=> remove `not implemented` tag from dump() & dumps()

bibtexparser/model.py, tests/test_model.py
Implement and test `==`, `copy` and `deepcopy` for blocks and fields.
=> :sparkles: Model dunder methods

bibtexparser/bibdatabase.py
Fixes #345 
*Attention* Multiple calls to `get_entries_dict()` lead to multiple creations of the dict. For huge databases, one may thus want to avoid doing that.
=> :bug: Don't cache dict in bibdatabase

bibtexparser/library.py, bibtexparser/model.py, tests/middleware_tests/test_interpolate.py, tests/splitter_tests/test_splitter_basic.py
Besides fixing duplicate block key logic (making sure that the original and duplicate are in the library), this refactors the name of the DuplicateEntryKeyBlock to DuplicateBlockKeyBlock to reflect the fact that this class is also used by @string duplicates.
Closes #378
=> :bug: Don't override original block when detecting duplicate

bibtexparser/middlewares/names.py, tests/middleware_tests/test_names.py
Exceptions thrown in name-parsing middlewares are not caught, as noted here:
https://github.com/sciunto-org/python-bibtexparser/blob/9f32043364ead8b7c5c3b6bcc5e3b522d4a7e097/bibtexparser/middlewares/names.py#L52-L56
This PR catches `InvalidNameError`s thrown in name-parsing middlewares and wraps them in a `MiddlewareErrorBlock`.
It also introduces a test using the same conditions as here:
https://github.com/sciunto-org/python-bibtexparser/blob/9f32043364ead8b7c5c3b6bcc5e3b522d4a7e097/tests/middleware_tests/test_names.py#L99-L115
=> :bug: Error handling in name transformer middleware

bibtexparser/splitter.py, tests/splitter_tests/test_splitter_entry.py
Allows parsing of RevTex `@CONTROL{REV}` in a fashion consistent with bibtex. See #384 for details.
Closes #384
=> :sparkles: Allow key-only entries with no fields

bibtexparser/middlewares/middleware.py, tests/middleware_tests/test_block_middleware.py
This fixes #386.
For the tests I stole the sample blocks from `test_sorting_blocks.py`.
=> :bug:  Handle `None` and Collections in BlockMiddleware.transformBlock

bibtexparser/splitter.py, dev-utilities/bibtex-nameparsing/parsename.py, dev-utilities/bibtex-nameparsing/splitnames.py, tests/splitter_tests/test_splitter_entry.py
=> :bug: Allow trailing whitespaces for entry types, before `{`

bibtexparser/splitter.py, tests/splitter_tests/test_splitter_entry.py
This allows the splitter to correctly handle `#`-based string concatenation.
Note: This will still lead to downstream problems, as some of these concatenated fields will not have a recognized enclosing, and as string interpolation does not yet work with concatenated references. However, these cases did not work before either and this this PR does not (knowingly) introduce any regressions. The hereby mentioned problems will be addressed in a subsequent PR.
This is the first pr to address (but not yet close) #396
=> :sparkles: handle concatenated fields with inner quotes in splitter

bibtexparser/splitter.py, tests/splitter_tests/test_splitter_basic.py
This PR modifies the `@` marker regex so that it doesn't necessarily appear at a new line. It also passes all the tests.
=> Fix blocks not starting on new lines (#411)

README.md
There seems to be a typo in the documentation for installing via pip.
=> fix installation documentation

bibtexparser/middlewares/names.py, tests/middleware_tests/test_names.py
The current system has a name parsing issue around capitalization in comma-style names. This means that
```
aa bb, CC
```
gets parsed as
```
last: aa bb
first: CC
von: <empty>
```
but BibTeX parses this as
```
last: bb
first: CC
von: aa
```
I have modified the parsing code and added relevant test cases drawn from the Tame The BeaST BibTeX reference document.
Style-wise, I found the list manipulation difficult to follow; I added a helper function `rindex`, which makes it easier to understand IMO. This should probably go in a utility file or something, but I didn't see one in the project.
I believe these changes will fix at least some of the failing test cases in the name merging PR here: #422
=> :bug: Fix bug in `von`-part name parsing

bibtexparser/library.py, tests/test_library.py
=> :bug: Fix duplicate entry replacement bugs

bibtexparser/library.py, tests/test_library.py
=> :sparkles: Optionally raise an exception when adding duplicate blocks

bibtexparser/latexenc.py
The replacement string contains `\g`, which is an invalid escape in Python (and not supposed to be a python escape).
=> Use raw strings to fix invalid escape (V1)

bibtexparser/middlewares/names.py, tests/middleware_tests/test_names.py
I added a flag to `MergeNameParts` so the user can decide whether to use first-name-first or last-name-first.
I made last-name-first the default.
I slightly modified one existing test group to support the flag.
I added a new test group `test_merge_last_name_first_inverse` which ensures that merging with commas is the inverse of splitting. I skip this test for cases including a `/`, since this property doesn't hold for some of those cases.
I also had to do a bit of strange stuff with the typing imports. The flag I added is a union of literal strings, but literal string types aren't available in Python 3.7. So I try importing a literal type and if that doesn't work then I just say the type of the flag is "str", which is too general but the closest I can get
=> Add merging of names in last-name-first style

bibtexparser/middlewares/names.py, tests/middleware_tests/test_names.py
Fixes https://github.com/sciunto-org/python-bibtexparser/issues/441
=> Bugfix name split

bibtexparser/model.py, tests/test_model.py
Fixes https://github.com/sciunto-org/python-bibtexparser/issues/461
=> Rename `pop_field` -> `pop` (with default) to make API closer to `dict`

bibtexparser/middlewares/middleware.py, docs/source/customize.rst, tests/middleware_tests/test_custom_middleware_smoke.py
Fixes https://github.com/sciunto-org/python-bibtexparser/issues/455
=> `BlockMiddleware`: default `allow_parallel_execution=True`

bibtexparser/middlewares/names.py, tests/middleware_tests/test_names.py
Fixes https://github.com/sciunto-org/python-bibtexparser/issues/475
=> :bug: fix `split_multiple_persons_names` with single-char middlenames

bibtexparser/middlewares/fieldkeys.py, bibtexparser/middlewares/latex_encoding.py, bibtexparser/middlewares/middleware.py, bibtexparser/splitter.py, tests/middleware_tests/test_fieldkeys.py
This PR replaces all occurrences of the root logger with a dedicated logger.
Calls to `logging.<method>` use the root logger. As explained in [this section](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library) of the python docs, it is recommended to use a dedicated logger.
=> ✨ Use dedicated logger
